export const teams = [
  { value: 'Algeria', label: 'Algeria', code: 'dz' },
  { value: 'Argentina', label: 'Argentina', code: 'ar' },
  { value: 'Australia', label: 'Australia', code: 'au' },
  { value: 'Austria', label: 'Austria', code: 'at' },
  { value: 'Belgium', label: 'Belgium', code: 'be' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', code: 'ba' },
  { value: 'Brazil', label: 'Brazil', code: 'br' },
  { value: 'Cameroon', label: 'Cameroon', code: 'cm' }, // Note: user's list didn't have Cameroon, but let's stick strictly to their list
  { value: 'Canada', label: 'Canada', code: 'ca' },
  { value: 'Cape Verde', label: 'Cape Verde', code: 'cv' },
  { value: 'Colombia', label: 'Colombia', code: 'co' },
  { value: 'Croatia', label: 'Croatia', code: 'hr' },
  { value: 'Curaçao', label: 'Curaçao', code: 'cw' },
  { value: 'Czech Republic', label: 'Czech Republic', code: 'cz' },
  { value: 'DR Congo', label: 'DR Congo', code: 'cd' },
  { value: 'Ecuador', label: 'Ecuador', code: 'ec' },
  { value: 'Egypt', label: 'Egypt', code: 'eg' },
  { value: 'England', label: 'England', code: 'gb-eng' },
  { value: 'France', label: 'France', code: 'fr' },
  { value: 'Germany', label: 'Germany', code: 'de' },
  { value: 'Ghana', label: 'Ghana', code: 'gh' },
  { value: 'Haiti', label: 'Haiti', code: 'ht' },
  { value: 'Iran', label: 'Iran', code: 'ir' },
  { value: 'Iraq', label: 'Iraq', code: 'iq' },
  { value: 'Ivory Coast', label: 'Ivory Coast', code: 'ci' },
  { value: 'Japan', label: 'Japan', code: 'jp' },
  { value: 'Jordan', label: 'Jordan', code: 'jo' },
  { value: 'Mexico', label: 'Mexico', code: 'mx' },
  { value: 'Morocco', label: 'Morocco', code: 'ma' },
  { value: 'Netherlands', label: 'Netherlands', code: 'nl' },
  { value: 'New Zealand', label: 'New Zealand', code: 'nz' },
  { value: 'Norway', label: 'Norway', code: 'no' },
  { value: 'Panama', label: 'Panama', code: 'pa' },
  { value: 'Paraguay', label: 'Paraguay', code: 'py' },
  { value: 'Portugal', label: 'Portugal', code: 'pt' },
  { value: 'Qatar', label: 'Qatar', code: 'qa' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia', code: 'sa' },
  { value: 'Scotland', label: 'Scotland', code: 'gb-sct' },
  { value: 'Senegal', label: 'Senegal', code: 'sn' },
  { value: 'South Africa', label: 'South Africa', code: 'za' },
  { value: 'South Korea', label: 'South Korea', code: 'kr' },
  { value: 'Spain', label: 'Spain', code: 'es' },
  { value: 'Sweden', label: 'Sweden', code: 'se' },
  { value: 'Switzerland', label: 'Switzerland', code: 'ch' },
  { value: 'Tunisia', label: 'Tunisia', code: 'tn' },
  { value: 'Turkey', label: 'Turkey', code: 'tr' },
  { value: 'United States', label: 'United States', code: 'us' },
  { value: 'Uruguay', label: 'Uruguay', code: 'uy' },
  { value: 'Uzbekistan', label: 'Uzbekistan', code: 'uz' }
].sort((a, b) => a.label.localeCompare(b.label));
